### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by auvo1001** [jselmani/cyclops#9]
Dear Jiel, I'm new to VR. Could you provide a bit more detail on how to set this up?
Thanks

**Comment by jselmani** [comment]
Hey @auvo1001, definitely.  

A few contributors and I are working on a brand new system that should be ready for release by next week. This is old and outdated and I think you would really like the new implementation much more.  I will be sure to have documentation ready for you when the new release is ready and will be more available to answer questions then!

Thanks for taking a look at my project.  I'll be in touch soon!

**Comment by auvo1001** [comment]
Dear Jiel,

Thank you very much for your help. I’ll be waiting for the release then.

Have a great week.

Best,

-Au


On April 11, 2018 at 8:58:44 PM, Jiel (Jyle) Selmani (
notifications@github.com) wrote:

Hey @auvo1001 <https://github.com/auvo1001>, definitely.

A few contributors and I are working on a brand new system that should be
ready for release by next week. This is old and outdated and I think you
would really like the new implementation much more. I will be sure to have
documentation ready for you when the new release is ready and will be more
available to answer questions then!

Thanks for taking a look at my project. I'll be in touch soon!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jselmani/OculusDataExtractor/issues/9#issuecomment-380670650>,
or mute the thread

**Comment by jselmani** [comment]
@auvo1001 The new version of our project will be posted in the next two weeks.  I will message you when it is up for you to use!  Keep an eye out in your email!

**Comment by auvo1001** [comment]
Dear Jiel,

Thanks for the update. I’ll keep an eye on your email.

Have a great week


On April 17, 2018 at 5:54:02 PM, Jiel (Jyle) Selmani (
notifications@github.com) wrote:

@auvo1001 <https://github.com/auvo1001> The new version of our project will
be posted in the next two weeks. I will message you when it is up for you
to use! Keep an eye out in your email!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jselmani/OculusDataExtractor/issues/9#issuecomment-382207290>,
or mute the thread

**Comment by jselmani** [comment]
@auvo1001 the newest release of this project is up and running.  Please read the documentation to get started.  If any clarification is needed, please feel free to submit another issue.

**Comment by auvo1001** [comment]
Got it. Thanks .I’ll take a look.


On May 3, 2018 at 10:44:29 AM, Jiel (Jyle) Selmani (notifications@github.com)
wrote:

@auvo1001 <https://github.com/auvo1001> the newest release of this project
is up and running. Please read the documentation to get started. If any
clarification is needed, please feel free to submit another issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jselmani/cyclops/issues/9#issuecomment-386378503>, or mute
the thread
